<a href="https://colab.research.google.com/github/ffreirea1988/usm/blob/main/Ejemplo_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [69]:
#Declarar arreglo en una variable
x = np.array([[1,2,3]
              ,['a','b','c']
              ,[100,200,'abc']])
y=np.array([[1],[2],[3],[4],[5]])
print(x.shape)
print(y.shape)
print(y)

(3, 3)
(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [62]:
a = np.empty(3)
print(a)

[0.5837658  0.39484981 0.72453464]


In [38]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [27]:
c=np.identity(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
d = np.full(5,3)
print(d)

[3 3 3 3 3]


In [53]:
e = np.arange(1,10,1)
print(e)

[1 2 3 4 5 6 7 8 9]


In [59]:
f = np.linspace(0,100,5)
print(f)

[  0.  25.  50.  75. 100.]


In [61]:
g = np.random.random(3)
print(g)

[0.5837658  0.39484981 0.72453464]


In [68]:
x = np.array([[[1,2,3],['a','b','c']]
              ,[[1,2,3],['a','b','c']]
              ,[[1,2,3],['a','b','c']]])
print(x.shape)
print(x)

(3, 2, 3)
[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['1' '2' '3']
  ['a' 'b' 'c']]

 [['1' '2' '3']
  ['a' 'b' 'c']]]
